### ISSUE TITLE
D1 Differential Coding

### ISSUE THREAD

**Issue by anson304** [powturbo/TurboPFor#103]
Hello,

I am looking to use p4nd1enc128v16, however, I looked at the research paper you referenced and it says D1 differential encoding is the slowest of D1, D2, DM, and D4. Is there a specific reason D1 was chosen?

**Comment by powturbo** [comment]
For distributions with a strictly increasing sequence like the DocIds in an inverted-index D1 has the best compression, especially for frequent terms. You have often blocks (128/256 integers) with a delta 1 in frequent terms, this will be compression to 1 byte (bit length).
The others D2,D4 can be faster, but the difference using simd is not so large to have an influence in the query processing.

**Comment by anson304** [comment]
Thanks for your explanation
