### ISSUE TITLE
Just some questions about TurboPFor Implementation

### ISSUE THREAD

**Issue by anson304** [powturbo/TurboPFor#106]
Hello,

Sorry for asking so many questions, but I just have a last few that I need for my research project. 

1. Does turbopfordelta scalar (p4d1dec32) use blocks of 256 integers? My results show that the compression ratio is the exact same as turbopfordelta256 (p4d1dec256v32) at around 1,754,373,849 bytes for my UST posting list. However, the compression ratio of turbopfordelta128 is better than both, at 1,464,995,033. I think this may also explain why turbopfor1delta28 is 5-15% faster for decompression of my index. I did some profiling and found that turbopfordelta256 uses more micro-instructions using the Intel vtune profiler when answering the same queries (this is unusual since SIMD should reduce the number of instructions)

2. What method of bit width selection do you use for turbopfor? There are different methods, such as threshold for majority of blocks (normal pfordelta), optimal bitwidth (OptPfordelta) etc.

3. In general do you select which block type is optimal for the next 256 integers. In your analaysis document, you say it chooses the best block type, but do not go into any details.

Thanks for your time, it's fine if you do not have the time to go into the details. I just want to be as accurate as possible when writing the paper.

**Comment by powturbo** [comment]
1. Only functions with 256 in the name are using 256 integers, all other functions use 128.
   If the d functions compress better than d1, then your sequence is not strictly increasing (assuming turbopfordelta128 = vp4denc32). 
2.The bit width with the best compression is used in the coding. There are different build in algos in TurboPFor (vp4) functions: bitpacking, PFor, Variable byte, constant.
3.All relevant bit sizes are examined, the best algo and the best bit width with maximal compression (regardless of speed) is used to encode all 128/256 integers in the block.
Feel free to ask me about TurboPFor. I'm glad you have interest in it,  especially  in the most complex part (idxqry.c).
After many years, TurboPFor is still SOTA. I have more ideas how to possibly improve it with novel algos, but I have actually no time for such a complex thing.

**Comment by anson304** [comment]
Thanks for answering all my questions :) I'd be interested in hearing about what ideas you have for improving these algorithms.

**Comment by powturbo** [comment]
Note that for the vp4 functions, the compression is never worse than bitpacking.
