### ISSUE TITLE
p4ddec32

### ISSUE THREAD

**Issue by anson304** [powturbo/TurboPFor#107]
Hello, thanks for answering my previous questions.

Does p4ddec32 use the same block size as p4ddec128v32? They result in the same compressed size. Last time you said that "Only functions with 256 in the name are using 256 integers", however, the compressed size seems to be the same even though 128 should compress better

**Comment by powturbo** [comment]
> Does p4ddec32 use the same block size as p4ddec128v32? 

Yes. 

> however, the compressed size seems to be the same even though 128 should compress better

Allmost always if you have an increasing sequence, however there can be exceptions with a marginal difference.
The "d" functions (like p4ddec32) are normally used for increasing sequences, the "d1" for strictly increasing 
otherwise it's better to use the "z" (delta zigzag) functions.
