### ISSUE TITLE
Cross-compiling for iOS

### ISSUE THREAD

**Issue by alexswerner** [powturbo/TurboPFor#108]
I'm successfully using the library on Linux on x64_64. Now I'm trying to compile this for iOS under OSX using clang. iOS not mentioned in the README, but was mentioned in #43. Maybe this is of general interest, so here is what I face

```
export CC=$(xcrun --sdk iphoneos --find clang)
export CFLAGS="-isysroot $(xcrun --sdk iphoneos --show-sdk-path) -arch arm64"
make libic.a
clang: error: the clang compiler does not support '-march=corei7=avx'
```

This obviously happens because the OS/platform detection runs `uname -s` and `uname -m` and goes from there. As a quick solution, I removed everything between `--- OS/ARCH ---` and `endif` in line 77. Now `sys/malloc.h` is not found because with the define `__APPLE__` this is the include used. I tried, but the iOS SDK has no `sys/malloc.h` but instead provides `malloc/malloc.h`.

**Comment by powturbo** [comment]
I've updated the package to support ios including malloc. The platform is detected by checking for the string "iPhone"
that should be contained in "uname -m". 
Can you please, post "uname -m" otherwise?
