### ISSUE TITLE
-E option

### ISSUE THREAD

**Issue by ordinaryorange** [powturbo/TurboPFor#114]
I notice some of the benchmarks use an `-E` argument to icapp and I cannot find any documentation on it.
Can you enlighten what are the valid args are and what this flag actually does please ?

**Comment by powturbo** [comment]
In icapp, the functions with the numbers 80-109 are using a compression codec after some transformations e.g. transpose. 
You can specify -Ezstd,#, -Elz4,#, -Eturborc,#  (#=level)

**Comment by pps83** [comment]
> I notice some of the benchmarks use an `-E` argument to icapp and I cannot find any documentation on it. Can you enlighten what are the valid args are and what this flag actually does please ?

I used some of the functions with that secondary codec, added a cmd line param for `icapp` to be able to specify it, and only after I added all the code to handle it, I noticed that there is that `-E` param that does [exactly the same job](https://github.com/powturbo/TurboPFor-Integer-Compression/pull/128#issuecomment-1951411018). PR to add usage is still pending ...
