### ISSUE TITLE
add p4dnenc* functions in vp4dc.h header

### ISSUE THREAD

**Issue by AdrianYu** [powturbo/TurboPFor#12]
It is not rare that we have some blocks of data in hand which aren't of the length of P4DSIZE. And since the lib has already got this functionality. It should be easy to just add several function declarations in the header.

**Comment by powturbo** [comment]
Thanks for reporting. 
I'm currently improving and reviewing this part and other functions in TurboPFor. Stay tuned for the next version.

**Comment by powturbo** [comment]
I've updated the TurboPFor package. You can now specify the size in the parameter n (maximum=256).
128/256 are used for the SSE/AVX2 functions.
