### ISSUE TITLE
SIGABRT while using p4enc64.

### ISSUE THREAD

**Issue by jeetu-raj** [powturbo/TurboPFor#14]
```
#include "conf.h"
#include "bitpack.h"
#include "vint.h"		
#include "bitutil.h"
#include "vp4.h"


typedef uint64_t LONG;


int main(LONG argc, char** argv) {
	LONG *array = (LONG *)malloc(sizeof(LONG)*5);
	array[0] = 24520120;
	array[1] = 29620120;
	array[2] = 42420120;
	array[3] = 20124222;
	array[4] = 4294967295;

	unsigned char* out = (unsigned char *)malloc(5*10*sizeof(unsigned char));
	unsigned char * op = p4enc64(array, 5, out);
	printf("%d\n",(int)(op-out) );
	

	LONG *capacity = (LONG *)malloc(sizeof(LONG)*5);
	unsigned char * op2 =  p4dec64(out, 5, capacity);
	printf("%d\n",(int)(op2-out) );

}


```

When attempting to use p4enc64 in above code, the following error is raised.

 malloc.c:2372: sysmalloc: Assertion `(old_top == (((mbinptr) (((char *) &((av)->bins[((1) - 1) * 2])) - __builtin_offsetof (struct malloc_chunk, fd)))) && old_size == 0) || ((unsigned long) (old_size) >= (unsigned long)((((__builtin_offsetof (struct malloc_chunk, fd_nextsize))+((2 *(sizeof(size_t))) - 1)) & ~((2 *(sizeof(size_t))) - 1))) && ((old_top)->size & 0x1) && ((unsigned long) old_end & pagemask) == 0)' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff700dc37 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.

**No issue occurs with  uint32_t and also when malloc is not used.**

Please correct me if there is any issue with the code. I am trying to use TurboPFor in my code for compressing 64-bit unsorted integer arrays. Also I am having trouble with allocating the right buffer size for the compressed array.What is the minimum buffer size I can allocate safely while using p4enc64 for integer array of size n?

**Comment by powturbo** [comment]
It is recommended to reserve an overhead of +32 elements for input and output array, as the scalar bitpacking functions are actually working on blocks of 32 elements.

**Comment by jeetu-raj** [comment]
Allocating overhead for 32 elements worked but I also had to allocate more space for the compressed buffer. Even though the difference between start and end pointers for the buffer was 21, I had to allocate much more than that. How much should i allocate for the buffer?

**Comment by powturbo** [comment]
For "p4" and "bitpack" functions s compressed buffer of "n" elements with size "s" cannot be larger than "CSIZE=(n*s+7)/8+1" bytes. This corresponds to bitpacking. Minimum memory buffer size = CSIZE+REGSIZE bytes. Overhead is REGSIZE = 8.

**Comment by jeetu-raj** [comment]
```
	LONG *array = (LONG *)malloc(sizeof(LONG)*37);
	array[0] = 24520120;
	array[1] = 29620120;
	array[2] = 42420120;
	array[3] = 20124222;
	array[4] = 4294967295;

	//5 elements of 8 bytes -- CSIZE = 7 

	// unsigned char* out = (unsigned char *)malloc(15); // SIGABRT raised
	// unsigned char* out = (unsigned char *)malloc(48); //-- assuming 37 elements CSIZE = 39  - still SIGABRT
	unsigned char* out = (unsigned char *)malloc(15*10); //-- works fine

	unsigned char * op = p4enc64(array, 5, out);
	printf("%d\n",(int)(op-out) );    // output - 21
	

	LONG *capacity = (LONG *)malloc(sizeof(LONG)*37);
	unsigned char * op2 =  p4dec64(out, 5, capacity);
	printf("%d\n",(int)(op2-out) );

```
I tried with the size you suggested, it still is leading to  same error. Please correct me if i am making any trivial mistake.

**Comment by powturbo** [comment]
`

        #include "conf.h"
        #include "bitutil.h"  
        #include "vp4.h"
        
        typedef uint64_t u64;

        int main(u64 argc, char** argv) {
        unsigned cnt = 5, a = SIZE_ROUNDUP(cnt,32);
	u64 *array = (u64 *)malloc(sizeof(array[0])*a);
	array[0] = 24520120;
	array[1] = 29620120;
	array[2] = 42420120;
	array[3] = 20124222;
	array[4] = 4294967295;
        //for(int i=0;i<cnt;i++) array[i] = (u64)-1; 
      
        int b;
	printf("cnt=%d bit64=%d\n", cnt, b = bit64(array,cnt) ); 
	unsigned char* outb = (unsigned char *)malloc( ((b+7)/8)*a); 

	unsigned char* op = bitpack64(array, cnt, outb, b);
	printf("bitpack64=%d\n",(int)(op-outb) );   
 
	unsigned char* out = (unsigned char *)malloc( ((b+7)/8)*a+1);
	op = p4enc64(array, cnt, out);
	printf("p4enc64=%d\n",(int)(op-out) );
	
	u64 *capacity = (u64 *)malloc(sizeof(capacity[0])*a);
	unsigned char *op2 =  p4dec64(out, cnt, capacity);
	printf("%d\n",(int)(op2-out) );
        }
`
This is the minimum size needed for each function. Trying to allocate 1 byte less, leads to a segfault.

**Comment by jeetu-raj** [comment]
Thanks!!

**Comment by jeetu-raj** [comment]
```
int main()
{
	unsigned cnt = 577;  //no issue if cnt <= 576 
	unsigned a = SIZE_ROUNDUP(cnt,32);

	u64 *array = (u64 *)malloc(sizeof(array[0])*a);

	int i = 0;
    for(i=0;i<cnt;i++)
    {
    	if(i%2==0)		
    	{			
    		array[i] =  rand();     //or any integer with size 32 bit
    		// array[i] = (u64)-1; //no issue on using this one
    	}
    	else
    		array[i] = (u64)-1; 
    }

	int b;
	printf("a=%d cnt=%d bit64=%d\n",a, cnt, b = bit64(array,cnt) ); 

	unsigned char* outb = (unsigned char *)malloc( ((b+7)/8)*a); 

	unsigned char* op = bitpack64(array, cnt, outb, b);
	printf("bitpack64=%d\n",(int)(op-outb) );   


	unsigned char* out = (unsigned char *)malloc( ((b+7)/8)*a+1);

	op = p4enc64(array, cnt, out);
	printf("p4enc64=%d\n",(int)(op-out) );

	u64 *capacity = (u64 *)malloc(sizeof(capacity[0])*a);
	unsigned char *op2 =  p4dec64(out, cnt, capacity);
	printf("%d\n",(int)(op2-out) );
}
```

The above code is causing Seg fault with the following backtrace

Program received signal SIGSEGV, Segmentation fault.

0x0000000000aa22ab in p4enc64 (
    in=<error reading variable: Cannot access memory at address 0x61e74e8b>, 
    in@entry=<error reading variable: Cannot access memory at address 0x61e74eab>, 
    n=<error reading variable: Cannot access memory at address 0x61e74e87>, 
    n@entry=<error reading variable: Cannot access memory at address 0x61e74eab>, 
    out=<error reading variable: Cannot access memory at address 0x61e74e7b>, 
    out@entry=<error reading variable: Cannot access memory at address 0x61e74eab>) at temp/vp4c.c:329
329	  out = TEMPLATE2(_P4ENC, USIZE)(in, n, out, b, bx); 

I am not able to to understand why this is happening, the in and out arrays are being allocated with suitable sizes and buffer  is also properly  allocated. It happens when cnt >= 577 and when i have elements inserted with the following pattern:
```
    	if(i%2==0)		
    	{			
    		array[i] =  rand();       //or any integer with size 32 bit
    		// array[i] = (u64)-1;   //no issue on using this one
    	}
    	else
    		array[i] = (u64)-1; 
```

**I came across the above case while trying to insert the elements in out.txt (which are not more than 32 bits). The above case is different but similar fault is raised with out.txt too. Please have a look at these cases.**
[out.txt](https://github.com/powturbo/TurboPFor/files/1060137/out.txt)

**Comment by powturbo** [comment]
`Change malloc(sizeof(capacity[0])*a) to malloc(sizeof(capacity[0])*(a+64))`

I'll take this issue into account in the next update, trying to avoid these segfaults.

**Comment by powturbo** [comment]
In general and for better compression it is not recommended to use p4 TurboPFor functions with n > 256.
You can compress large arrays in chunks of 128 or 256 elements or simply use p4nenc functions.
(see icbench.c).
