### ISSUE TITLE
Cannot build libic.so under Linux (Ubuntu)

### ISSUE THREAD

**Issue by mvanleeu** [powturbo/TurboPFor#16]
Hi Hamid,

after buildign the icbench tool via the makefile, I tried tobuild libic.so by following the instructions in java/jicbench.java with some small adaptations detailed below. I also found and tried #5 but no luck. I always get compilation error for libic.so.

My adaptations to the build instructions
1 - generate header jic.h 
$ cd ~/TurboPFor/java
$ javah -jni jic
$ ~~cp jtrle.h ..~~  =>   __cp jic.h ..__
2 - Compile jic and jicbench
$ javac jic.java
$ javac jicbench.java
3 - compile & link a shared library
$ cd ~/TurboPFor
$ gcc -O3 -march=native -fstrict-aliasing -m64 -shared -fPIC -I/usr/lib/jvm/default-java/include -I/usr/lib/jvm/default-java/include/linux bitpack.c bitunpack.c ~~bitpackv.c bitunpackv.c vp4dc.c vp4dd.c~~ __bitpack.c bitunpack.c vp4c.c vp4d.c__ vsimple.c vint.c bitutil.c jic.c -o libic.so

==>Bunch of (repeating) warnings and errors: [compile_errors.txt](https://github.com/powturbo/TurboPFor/files/1157414/compile_errors.txt)

#### Environment:
Virtual machine running Ubuntu, 3 virtual CPUs, on a Haswell-based host.

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

$ gcc --version
gcc (Ubuntu 6.3.0-12ubuntu2) 6.3.0 20170406

$ java -version
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.17.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.131-b11, mixed mode)

**Comment by powturbo** [comment]
Thanks for reporting. The java interface and the build documentation is now updated. 
"libic.so" can be build now without errors (tested with gcc 6.3 + ubuntu).

**Comment by mvanleeu** [comment]
Hello,

Finally got the chance to test the changes you made.  liobic.so now compiles without problems. Thanks.

But I still face some issues:
in java/jic.java in the static section at the bottom, I had to comment the usage of System.load (which hardcodes the location where the compiled .so file is searched for), and uncomment System.loadLibrary(....), as this is the "generic way", but correct the name of the library string to "ic". So the right string to load "libic.so" is:
`System.loadLibrary("ic") ;`

Then, next correction would be in the instructions in jicbench.java, 
5 - start jicbench
**cd ~/TurboPFor/java**
$ java jicbench   ## with a "j"

After all that, the problem I have is when I run the java bench program, I get a
`libic.so: Undefined symbol:  p4ndec256v32` 

`$ nm -g libic.so`
output [here](https://github.com/powturbo/TurboPFor/files/1207198/nm.txt)
