### ISSUE TITLE
undefined reference to `p4enc64'

### ISSUE THREAD

**Issue by jezwhite** [powturbo/TurboPFor#17]
Hi,

I wanted to play around with Floating Point compression and I thought I could just simply do:

```
#include "fp.h"
#include "fp.c"
```

to an existing project, but then I get:

```
undefined reference to `p4enc64'
undefined reference to `p4enc64'
```

I had a look arround the code but couldn't seem to find p4enc64 or p4dec64? So I assume I am doing something wrong. Using the latest code from github, with Mingw64.

**Comment by powturbo** [comment]
you must link with "vp4c.o" and "vp4d.o".
You can use the TurboPFor makefile to build these files or add your test program to the this makefile.

example (see the "ictest" line in the makefile) :
fptest:   fptest.o $(ICLIB)
	$(CC) $^ $(LDFLAGS) -o fptest

and build with:
"make fptest"
