### ISSUE TITLE
direct access for delta compression?

### ISSUE THREAD

**Issue by phoenixCloak** [powturbo/TurboPFor#22]
is there any plan of direct access for delta compression?

**Comment by powturbo** [comment]
Unlike general purpose compression (ex. lz77) and other integer compression methods like QMX, SimdFastPFor, Simple-8b,... TurboPFor is especially designed for random access in mind. 
You can uses random access at the block level (128/256 integers). 
This is used for example in the invervetd index demo (see "idxqry.c"). 
Direct random access at the granularity level of individual values is actually possible for TurboPFor (p4encx/p4decx) and TurboPack (bitgetx). 
For delta encoding you can use TurboFor (bitfpack/bitfunpack). I have several other ideas, but I can't say more without implemenation. 
May be soon... Stay tuned! 
Might, I ask you, for which use case, you need random access?

**Comment by phoenixCloak** [comment]
1. offset tables of solid bitstream/bytestreams
2. implemenation of succinct data structurs' rank/select
