### ISSUE TITLE
recommended output buffer estimation

### ISSUE THREAD

**Issue by halayli** [powturbo/TurboPFor#25]
Is there a guidance on estimating the maximum output buffer required given N values of type T ?

**Comment by powturbo** [comment]
For the bitpacking functions of type T you need 1 + (MaxBits*(N+32)+7)/8 bytes per block.
Same for the TurboPFor (p4enc) functions, as p4enc never compress worse than bitpacking.
In  general it is simpler to use : 1 + (sizeof(T)*(N+32) per block (ex. 128/256).
32 elements as overhead to avoid segfault. 
For small block sizes as used in bitpack and p4enc (max=256 integers) it is better
to use a static buffer (no malloc).

Here is an example for p4nenc:

static size_t encode(uint32_t *input, size_t n, FILE *f) {
  unsigned char *out = malloc((n+127)/128+(n+32)*sizeof(uint32_t)); // 1 byte overhead per 128 integers 
  size_t sz = p4nenc32(input,n,out);
  sz = fwrite(out, 1, sz, f);  
  free(out);
  return sz;
}

int main() {
  uint32_t input[32] = {3, 4, 5, 6, 9, 10, 15, 17, 18, 333};
  size_t sz = encode(input, 10);  
  fprintf(stderr, "encoded into %lu bytes\n", sz);
}

**Comment by halayli** [comment]
Thanks!

One suggestion is to maybe create macros like `P4_UPPER_BOUND()`
