### ISSUE TITLE
Compilation and Linker errors for _TURBOPFOR-enabled idxcr and idxqry

### ISSUE THREAD

**Issue by cloudspeech** [powturbo/TurboPFor#27]
Hi,

I am trying to test the inverted-index tools idxcr/idxqry with the TurboPFor-compressed version of the index format, as a code comment claims this results in smaller index sizes (perhaps also faster speed?).

However, I seem unable to compile and link them. I'm on Ubuntu 16.04 with gcc 7.2.0, Intel Core  i7-7500U.

First, idxcr.c:123 misses some function arguments - I tried to supply them heuristically, not sure this is correct: 
-                 b = _p4dec32(ip+1, n-1, &bx);
+                 b = _p4dec32(ip+1, n-1, out, b, &bx);

Second, even after that I get linker errors when I modify the makefile to define the necessary
C-preprocessor symbol and then issue $ make search AVX2=1:

ifeq ($(UNAME), Linux)
search: CFLAGS += -D_TURBOPFOR=1
search: idxcr
endif

The linker errors are:
In function `main':
idxcr.c:123: undefined reference to `_p4dec32'
idxcr.c:146: undefined reference to `_p4dec32'
idxcr.c:146: undefined reference to `_p4dec128v32'
collect2: error: ld returned 1 exit status

idxrqry is similar.

Any fixes/patches to make this work?

Thanks a lot in advance, Markus

**Comment by powturbo** [comment]
I've made some corrections to the coding. 
It should work now.
use : 
`make TURBOPFOR=1` 

to compile "idxcr.c" & "idxqry.c" with the TurboPFor "p4d1enc" instead
of the default "bit packing"  functions .

**Comment by cloudspeech** [comment]
Hello powturbo,

the compilation works now, thank you for that. One index that was 111MB now compresses as 100MB, not bad.

However, in my tests I run into SIGSEVs for *idxqry* specific to TurboPFor-compressed indices in *some cases* now. After fiddling with valgrind and gdb and additional printfs, my suspicion is p4d1dec32 can cause memory corruption. 

As a result, for now I reverted back to TURBOFOR=0.

Sorry, can't narrow it down more at the moment - perhaps this can serve as a starting point?

**Comment by powturbo** [comment]
the compression ratio is depending on the distribution of your data. 

For indexes smaller that available memory, it is recommended to use bit packing, 
because it is faster.
