### ISSUE TITLE
Generate output file

### ISSUE THREAD

**Issue by jsv13** [powturbo/TurboPFor#28]
Hello,
is it possible to actually save the compressed output in a file? And to decompress it afterwards?
thanks.

**Comment by powturbo** [comment]
TurboPFor is a library and the provided tools "icapp" and "icbench" can be only used for in-memory benchmarking. To compression into a file, you simply need to read the file in blocks (for ex. w/ p4nenc32), compress and write the compressed blocks into a file.

**Comment by jsv13** [comment]
thanks for this information.
