### ISSUE TITLE
Compilation issue vbd1dec32, BITDIZERO32

### ISSUE THREAD

**Issue by ofrei** [powturbo/TurboPFor#30]
I'm getting an error (with ``gcc (GCC) 4.9.0``):
```
CMakeFiles/myproject.dir/TurboPFor/vint.c.o: In function `vbd1dec32':
vint.c:(.text+0xb472): undefined reference to `BITDIZERO32'
collect2: error: ld returned 1 exit status
```
Of note, I'm compiling just ``bitutil.c``, ``vint.c``, and ``vsimple.c``.
I think it has to do with the last ``#else`` fork in ``bitutil.h`` ``defined(__SSE2__)  && defined(USE_SSE)`` / ``defined(__AVX2__) && defined(USE_AVX2)``

**Comment by powturbo** [comment]
Please use the provided makefile to build the object files.
You need "-DUSE_SSE -mssse3" for bitutil.o
sse2 is the minimum required for TurboPFor.

**Comment by ofrei** [comment]
Thanks! I build with CMake - adding ``target_compile_definitions(bgmg-test PRIVATE USE_SSE)`` fixed the issue.
