### ISSUE TITLE
vsenc32 crashes if input contains zero values

### ISSUE THREAD

**Issue by ofrei** [powturbo/TurboPFor#31]
If I understood correctly, vsenc32/vsdec32 does not support zero values in the input stream. Is this correct? I encounter weird crashes (memory corruption), which go away as long as I avoid zero elements in the input stream. If this is the case, please add assert and/or short comment in documentation.
```
// vsencNN: compress array with n unsigned (NN bits in[n]) values to the buffer out. Return value = end of compressed output buffer out
// vsdecNN: decompress buffer into an array of n unsigned values. Return value = end of compressed input buffer in 
```

**Comment by powturbo** [comment]
No, you can compress any values with vsenc32/vsdec32 or other TurboPFor functions.
In contrast to other libraries, TurboPFor supports the full range of 8/16/32/64 bits integers.
You can use icapp for testing. See also: [Hello TurboPFor](https://github.com/powturbo/TurboPFor/issues/26). 
Please, send me your file, if the problem persists. 
Nevertheless, it is better to use the p4enc functions instead.

**Comment by ofrei** [comment]
Thanks! Found the problem, I used wrong size for output buffer - instead of P4NDEC_BOUND I just allocate exact amount of memory to store uncompressed data. ROUND_UP fixes my crashes.
```
#define ROUND_UP(_n_, _a_) (((_n_) + ((_a_)-1)) & ~((_a_)-1))
#define P4NENC_BOUND(n, size) ((n + 127) / 128 + (n + 32) * (size))
#define P4NDEC_BOUND(n, size) (ROUND_UP(n, 32) * (size))
```

**Comment by ofrei** [comment]
To double-check, macro ``P4NENC_BOUND`` and ``P4NDEC_BOUND`` are applicable to API in ``vsimple.h``?

**Comment by powturbo** [comment]
Use:
#define VSENC_BOUND(n, size) ((n + 32) * ((size)+1) )
#define VSDEC_BOUND(n, size) ((n + 32) * (size))

for "vsimple.h" or "vint.h"

**Comment by ofrei** [comment]
Thanks!
