### ISSUE TITLE
p4nzenc16 performance

### ISSUE THREAD

**Issue by NickSong** [powturbo/TurboPFor#32]
I was doing some benchmarking using your code, and was very interested with your p4nzenc16 and other algorithms defined in vp4.h. Below are the test results with our own data: 

icapp.exe -s2 ..\data\data
   E MB/s     size     ratio    D MB/s  function
   291.27     109183  83.30%  1213.63 p4nzenc16         ..\data\data
   296.54     109183  83.30%  1472.72 p4nzenc128v16     ..\data\data
 13107.20     131072 100.00% 11915.64 memcpy

As shown, the Encoding and Deconding speeds are much lower than your benchmarks. I think the reason should be on the data characteristics. Our data looks like the following int32 array:
3956541806 | 4021030862 | 4156167980 | 4292351536 | 122688988 | 306712316 | 340264262 | 429391892 | 4293721652 | 363856276 | 311752484 | 339799824| 4235594008 | 4524368 | 77400290 | 119604839 | 147588075 | 156565166 | 123075266 | 129103883 | 4290838339 | 114620947 | 47183905 | 13301076
4285659166 | 4236114193 | 4166384448 | 4157799805 | 4175364326 | 4183426246 | 4234216941 | 4256303196 | 13369437 | 4252698291 | 12388188 | 56166432
254473376 | 190640480 | 41675844 | 4243778848 | 4123848842 | 4021352164 | 4006412090 | 3940549509 | 2883989 | 4012638792 | 4077652372 | 4104654984
264900636 | 329517310 | 402456453 | 331937716 | 279507270 | 124447292 | 4257934256 | 4158318916 | 4276027312 | 4211534776 | 4081119688 | 3936678884
53674504 | 59572339 | 54197952 | 55901532 | 23461120 | 7207976 | 4273994955 | 4246338828 | 4284022907 | 4266917110 | 4243455526 | 4239261366
4124374812 | 4083874473 | 4060086691 | 4094035282 | 4155902560 | 4226682114 | 48958370 | 109907428 | 19136432 | 67767338 | 140248949 | 223478996
4278517578 | 4282253572 | 18153714 | 22609897 | 4287561290 | 4280549154 | 4287430841 | 8192371 | 983184 | 4294639905 | 6422579 | 15335227
4287365347 | 15073760 | 26148779 | 7601913 | 4272029419 | 4277928110 | 10486103 | 30277608 | 4292804642 | 25100410 | 10944260 | 4273405619
4290183352 | 4285399269 | 4980480 | 3211078 | 4284940362 | 4283039840 | 6488321 | 10158232 | 786522 | 9306149 | 4259602 | 4291821626
4288020496 | 4278124841 | 17105015 | 7012364 | 1179425 | 4279107371 | 4287561847 | 3539276 | 4292739123 | 786612 | 9109491 | 14483363
4278583511 | 721358 | 22741000 | 1048332 | 4281401193 | 4281597998 | 4291166556 | 22347807 | 8257644 | 20512778 | 13107137 | 4284219109
4290576569 | 15663574 | 35323624 | 3276322 | 4261543643 | 4276158780 | 13304084 | 34340846 | 12451881 | 39059472 | 6094518 | 4272881238

Question 1: **How should we compress such kind of data to achieve the results as shown in your benchmarks (> 1.3GB/s Encoding, > 5GB/s deconding, >2x compression ratio)?**

Question 2: **Do you have any documents regarding the mechanism of the p4nzenc16?**

**Comment by powturbo** [comment]
p4nzenc16 is for 16 bits data (0..65535) , you must use p4nzenc32 (icapp -s4 ..\data\data) with
32 bits raw data.
The compression ratio and also the speed is highly depending on the distribution of you data. 

From the small sample data provided, we can see that the difference between two successive values 
is very large, so not very good compressible. 

With icapp, you can test almost all TurboPFor functions.

p4nzenc is using the TurboPFor p4nenc function after the [zigzag](https://stackoverflow.com/questions/4533076/google-protocol-buffers-zigzag-encoding) encoding operation.

**Comment by NickSong** [comment]
Thanks for your advice.
The 32-bit compression is faster, but ratio is even worse, so I only choose 16 bits. 
550.25   18758328  88.28%  2329.77 p4nzenc128v32     ..\data\data
**Reading data in 16 bits, I found that some of the data seems to have a large, small rule. Is this the reason why 16bit has a better compression ratio?
114,64413,465,64416,952,64871,962,65209,996,145,1031,602,610,865,304,1354,65437,194,468,1003,65436,966,65024,1076,65500,129,65399,28,64408,65367,64391,64938,64324,65216,64503,64896,64890,64553,65264,64254,292,64481,17,65513,963,65144,1224,65366,580,64826,1089,34,1270,284
**In addition, I still don't know, after doing zigzag coding, what compression did p4nenc do, like bitcompress, remove the high zero bit?

**Comment by powturbo** [comment]
It is possible in some cases to have better compression with 16 bits.
However, you must consider if it is worth to use compression, when your data is
badly compressible.
There is a short description of TurboPFor in this [paper](http://www.cs.otago.ac.nz/homepages/andrew/papers/2016-2.pdf).

>remove the high zero bit? 
Yes

**Comment by NickSong** [comment]
Some of the data also have some 0, although the proportion is not high. Hey, try it **again~~.
4816,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,446,59408,2316,59944,5036,61440,5644,63610,5948,448,5372,3154,2962,4716,2304,6180,65241,347,2528,5284,65129,5512,62982,6476,65420,12,95,113,59644,64391,59624,62444,59588,64106,60712,62668,61948,61100,64359,59268,1177,59636,419,841,5588,63104,6064,65142,3174,62014,5704,65127,6632,1764,6684,4404,3382,5648
**Thanks again for the documentation provided.**
