### ISSUE TITLE
compile error undefined reference to `fseeko'

### ISSUE THREAD

**Issue by iceberg1369** [powturbo/TurboPFor#33]
I am trying to compile using mingw in windows. but it throws following error:

    g++ eliasfano.o vsimple.o transpose.o transpose_sse.o bitpack.o bitpack_sse.o bitunpack.o  bitunpack_sse.o vp4c.o vp4c_sse.o vp4d.o vp4d_sse.o bitutil.o fp.o vint.o ext/trlec.o ext/trled.o icbench.o plugins.o  -o icbench
    icbench.o:icbench.c:(.text.startup+0xbf2): undefined reference to `fseeko'
    icbench.o:icbench.c:(.text.startup+0xbfa): undefined reference to `ftello'
    icbench.o:icbench.c:(.text.startup+0xc1f): undefined reference to `fseeko'
    collect2.exe: error: ld returned 1 exit status
    makefile:291: recipe for target 'icbench' failed
    mingw32-make: *** [icbench] Error 1

**Comment by powturbo** [comment]
I don't know which mingw version you are using, but TurboPFor can be compiled under MingW64
without any issue. Please use the provided makefile.
Simply type "make" or "mingw32-make"
