### ISSUE TITLE
float16 lossy compression

### ISSUE THREAD

**Issue by yunhua-deng** [powturbo/TurboPFor#34]
There are ```padfloat32()``` and ```padfloat64()```, but no ```padfloat16()```, is it straightforward to create a float16 version based on the float32 version?

Also, what if I do the lossy compression for float16 data using ```icapp -f4 -g.001 float16data```?

**Comment by powturbo** [comment]
You can do something like (not tested):

static inline float16 fabs16(float16 d) { return d < 0?-d:d; } // write your own fabs16
#define ctof16(u) *(float16 *)u

static inline float16 efloat16(float16 d, float e, int lg2e) {
  uint16_t u, du = ctou16(&d);
  int      v = (du>>10 & 0x1f)-15;  // mantissa=10 bits, exponent=5bits, bias=15
  if((v = 12 - v - lg2e) <= 0) return d;
  v = v > 10?10:v;
  do u = du & (~((1u<<(--v))-1)); while(fabs16((ctof16(&u) - d)/d) > e); 
  return ctof16(&u);
}

void padfloat16(float16 *in, size_t n, float16 *out, float e) { int lg2e = -log(e)/log(2.0); float16 *ip; for(ip = in; ip < in+n; ip++,out++) *out = efloat16(*ip, e, lg2e); }
 
> icapp -f4 -g.001 float16data
it is not possible to use -f4, if your data is stored as binary 16 bits floats.
You must adapt "icapp.c" to use the new padfloat16.

**Comment by yunhua-deng** [comment]
With the help from this project http://half.sourceforge.net/, I managed to make the code work for float16 (tested).
```
#include <stdint.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include "half.hpp"
using half_float::half;

#define ctou16(_cp_) (*(unsigned short *)(_cp_))
#define ctof16(_cp_) (*(half *)(_cp_))

static inline half efloat16(half d, half e, int lg2e) 
{
    uint16_t u, du = ctou16(&d);
    int v = (du>>10 & 0x1f)-15; // mantissa=10 bits, exponent=5bits, bias=15
    if ((v = 12 - v - lg2e) <= 0) return d;
    v = (v > 10) ? 10 : v;
    do { 
        u = du & (~((1u<<(--v))-1)); 
    } while (fabs((ctof16(&u) - d)/d) > e);    
    return ctof16(&u);
}

// Lossy floating point conversion: pad the trailing mantissa bits with zeros according to the error e (ex. e=0.00001) 
void padfloat16(half *in, size_t n, half *out, half e) 
{ 
    int lg2e = -log(e)/log(2.0); 
    half *ip; 
    for (ip = in; ip < in+n; ip++,out++) { 
        *out = efloat16(*ip, e, lg2e); 
    }
}
```

Additionally, I am not so clear what the error actually means. For instance, `e=0.01` means every converted value has a difference of at most 0.01 to the original value, or relatively 1% loss?

**Comment by yunhua-deng** [comment]
According to my experiments, I think the error is the relative error, that is, e=0.01 will enforce the maximum loss by the lossy coversion being less than 1%. For example, original value is 0.100, converted value should be something like 0.0995 if e=0.01. Am I right?

**Comment by powturbo** [comment]
Nice you have manged to implement and tested the float16 routines.
Possibly, it is better to avoid the 16 - 32 float conversion by implementing your own fabs16.
> static inline half fabs16(half d) { return d < 0?-d:d; } // write your own fabs16
or
> static inline half fabs16(half d) { return (uint16_t)d & 0x7fff; }

Yes, e is the maximum relative error allowed, enforced in line "while(fabs...>e)".

In your case, you can also convert the float16 numbers to 16 bits integers multiplying the values by 100,
and then use the integer compression functions like p4enc16 or p4zenc16.
To test this, convert your data into a raw 16 bits integer or text format and use icapp.
It is also possible to use TurboTranspose in conjunction with lz77.

I've also found your issue: https://github.com/LLNL/zfp/issues/23
It will be nice, if you can publish a comparsion with zfp.

**Comment by yunhua-deng** [comment]
Thanks for suggesting the fabs16 and confirming the meaning of e.

Suprisingly, the padfloat16 is very slow, the speed is around 10 MB/s in my laptop. I didn't recognize this slowness in the icapp because the timing in fact does not include the lossy conversion. Is in general that such kind of relative-error bounded lossy conversion slow because it involves a loop inside the conversion?

Due to the slowness, I started considering your suggesting on converting float16 to int16. In fact, in my case, the float16 values are very small, and its range is something like 0.0000x~0.x. Hence, I am considering multiplying them by 1e5 to convert to int16 and try to use integer compressors.

It is nice to see that you found my issue in zfp, I will post the comparison once I finish testing the float16->int16 stuff.
