### ISSUE TITLE
Cannot build on Linux Mint 19 x86_64

### ISSUE THREAD

**Issue by VolodymyrB** [powturbo/TurboPFor#35]
I got next error for both gcc-7 and gcc-5 while executing make command:

/usr/lib/gcc/x86_64-linux-gnu/5/include/bmi2intrin.h:62:1: error: inlining failed in call to always_inline ‘_bzhi_u64’: target specific option mismatch
 _bzhi_u64 (unsigned long long __X, unsigned long long __Y)

**Comment by powturbo** [comment]
in which TurboPFor file?
If you have a AVX2 cpu try using "make AVX2=1"

**Comment by VolodymyrB** [comment]
Look like it is fp.c. Do not know is this right place to place full log, so I have placed it here https://pastebin.com/1wJ71DKD

**Comment by VolodymyrB** [comment]
Thank you, make AVX2=1 works fine, do not know why I have forgot too try this one.
