### ISSUE TITLE
Big endian Issues

### ISSUE THREAD

**Issue by NickSong** [powturbo/TurboPFor#36]
The big endian machine runs the bitpack algorithm, and the decompression is not correct. Has this algorithm considered the big end problem?

**Comment by powturbo** [comment]
The low level bitpack functions should normally work for big endian systems,
but the "bitn*" functions are using the "variable byte" functions, which are 
not endian neutral.
There is no plan to consider big endian processors in the near future.

**Comment by lemire** [comment]
My impression is that little endian dominates at this point and that most new systems support little endian computing. Is that not right?

**Comment by lemire** [comment]
(Java being the major exception.)

**Comment by NickSong** [comment]
Yes, most terminal devices are little endian, but there are many big endian in telecom systems. Maybe the purpose of using big endian is for efficiency. Although ther is not enough data to fill up 8 bytes of an int64, it still writes the data in int64 manner efficiently. We can adapt the algorithm to work with big endian, but it is difficult to make it fit to both little and big endians at the same time.

**Comment by powturbo** [comment]
@lemire : thanks for your contribution. Yes, allmost all current processors, GPUs and OSs use little endian. x86, arm, linux, windows... But, there are also microcontrollers using big endian (ex. atmel ).

@NikSong
I don't think, it  is difficult to adapt the coding for both little and big endian at the same time, if you're
working in memory.
If you want an interchangeable binary file format, then you must use special i/o wrappers like le32toh32 
(see include "endian.h" in linux).

**Comment by NickSong** [comment]
I have modified it to adapt big endian. Three file: 1 makefile    2 bitpack_.h   3bitunpack_.h
Just like below,  not use le32toh32.
#ifdef SMALL_ENDIAN
  do { 
    BITPACK64_9( in, out, start); PREFETCH(in); 
  } while(out<out_);
#else
  while((out_ - out) >= 9*4) { 
    BITPACK64_9( in, out, start); PREFETCH(in); 
  }
  if(out_>out){unsigned nb = out_ - out; BITPACK64_9_BIG_ENDIAN( in, out, nb, start);}
#endif
