### ISSUE TITLE
How do I build it into libic.so to use with java ?

### ISSUE THREAD

**Issue by kk00ss** [powturbo/TurboPFor#5]
Could you please suggest

**Comment by bp-alex** [comment]
For the benefit of others who find this ticket, follow the instructions in the `java/jicbench.java` file. 

You may need to modify the `gcc` command a little. I ended up with `gcc -O3 -march=native -fstrict-aliasing -m64 -shared -fPIC -Ijava -I/usr/lib/jvm/java-8-openjdk/include -I/usr/lib/jvm/java-8-openjdk/include/linux bitpack.c bitunpack.c bitpackv.c bitunpackv.c vp4dc.c vp4dd.c vsimple.c vint.c bitutil.c jic.c -o libic.so`.

Also note step 5 has a typo, you need `java jicbench` (add the `j` before `icbench`). I also needed to edit `jic.java` to use a hard-coded path to `libic.so` (the typical system library location and `-Djava.library.path` techniques did not work, but I didn't dig any further given I'm only benchmarking this library at present).

**Comment by powturbo** [comment]
Thanks for your contribution. 
jicbench is only a small demo to show the java functionality of TurboPFor.
I'll try to improve it in the next update.
For a complete benchmark, use the c "icbench" instead.
