### ISSUE TITLE
Hello world turbopfor makefile

### ISSUE THREAD

**Issue by Malfoy** [powturbo/TurboPFor#52]
Hi,

We want to use TurboPFor for our large scale applications.
We already use turboRLE which is very nice, thank you for your work.
We want to also use the p4enc* function and unfortunately, we find it hard to compile.
Our code is (as expected) very similar to the "hello world" you provided

#include <stdio.h>
#define NTURBOPFOR_DAC
#include "vp4.h"

#define P4NENC_BOUND(n) ((n+127)/128+(n+32)*sizeof(uint32_t))

int main(int argc, char* argv[]) {
      printf("Hello TurboPFor\n");
      int ar[32] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
      unsigned elnum = 10;
      unsigned char* compress_buf =  malloc(P4NENC_BOUND(elnum));
      int *uncompress_buf =  malloc((elnum+32)*sizeof(ar[0]));
  
      size_t compress_size = p4nenc32((uint32_t*)ar, elnum, compress_buf);
      printf("compress size is %lu\n", compress_size);
  
      size_t uncompress_size = p4ndec32(compress_buf, elnum, (uint32_t*)uncompress_buf);
      printf("uncompress size is %lu\n", uncompress_size);
}

Could you provide a corresponding minimalistic makefile that we could adapt as the repository makefile is quite dense and complex.

Thank you for your time.

**Comment by powturbo** [comment]
I've now a simplified makefile which compile under linux, windows, MacOs for amd64, arm64, power9 and other (see [travis build](https://travis-ci.org/powturbo/TurboPFor)).
Type make to build the static library "libic.a" + the benchmark "icapp".
Actually there is no "make install". 
Just include the main header files "vp4.h" "bitpack.h", "vint.h",... in your source files and link your program with "libic.a".
The "libic.a" supports sse+avx2. 
TurboRLE and TurboTranspose are also included.

**Comment by powturbo** [comment]
I hope this was helpful
