### ISSUE TITLE
Remove invalid references to USE_SSE, USE_AVX2

### ISSUE THREAD

**Issue by pps83** [powturbo/TurboPFor#53]
https://github.com/powturbo/TurboPFor/blob/5dff9d3fc120fafa13cedbc8ea0f249e8291215a/vs/vs2017/TurboPFor.vcxproj#L92

If you remove USE_SSE & USE_AVX2, why don't you grep entire repo to see if you have left overs here and there?..

**Comment by pps83** [comment]
Also, projects using turbopfor do not build now. I don't know what/why you change and test, but it's spiting tons of linker errors now.

**Comment by powturbo** [comment]
Please, be patient. I'll check also vc++.
USE_SSE & USE_AVX2 are no more needed, as avx2+sse will be automatically included.

**Comment by pps83** [comment]
Yes, I noticed that, it's a good change. Also, all these _sse files should be removed now from all projects/makfiles.

**Comment by powturbo** [comment]
well the _sse files can't be removed. We must have object files compiled with sse only (no avx and no with avx2).
We don't want compilers inserting other instructions (>sse) into the sse object files.

**Comment by pps83** [comment]
sse only is like 20 years old, right? Do you have specific reason to have sse-only builds?

regarding _sse and _avx files. Those are all compiled with the same compilation switches as other files. That is, if bitunpack_sse.c includes bitunpack.c then the result will the same as compiling bitunpack.c itself (if SSE2_ON was removed, then having bitunpack_sse.c becomes totally pointless). Also, bitunpack.c and bitunpack_sse.c are kind of weird. It's probably not even possible to run without sse nowadays anyway.

**Comment by powturbo** [comment]
with sse,  I'm referring to NON AVX2. The default/minimum compile is already set to sandy bridge (w/o avx) corei7 for all non avx2 files. The same library should also run on cpus without avx,avx2.

**Comment by powturbo** [comment]
I've now adapted the visual c++ project files. 
Minimum architecture is set to AVX for windows with vs.

.c and _sse.c are kept separetly for cpu's not supporting sse4.1 and for scalar/sse functions 
calling other scalar/sse functions. We don't want compilers inserting simd instructions
through autovectorization into the scalar object files.
