### ISSUE TITLE
[codestyle] Would be nice to remove all trailing whitespace

### ISSUE THREAD

**Issue by pps83** [powturbo/TurboPFor#54]
It's extreme how much trailing whitespace tp4 has all over the place.

**Comment by powturbo** [comment]
done!

**Comment by pps83** [comment]
still have lots of these:
![image](https://user-images.githubusercontent.com/1614246/71308678-ac3a9180-2429-11ea-8ab2-0434199ef5bb.png)
(ignore `ext`)

**Comment by powturbo** [comment]
must be ok now

**Comment by pps83** [comment]
Thanks, now it fixed.

**Comment by pps83** [comment]
@powturbo I don't know how you managed, but now it's absolutely infested with trailing whitespace. as if you took some old versions, worked with them and dumped into git. wtf
