### ISSUE TITLE
Do not self include .c files

### ISSUE THREAD

**Issue by pps83** [powturbo/TurboPFor#55]
https://github.com/powturbo/TurboPFor/blob/56e510087bde39bfadf55a3128f0751433c50e2b/vp4c.c#L53

That's simply confusing for anybody tracking the code. Split these files into .c files that change defines and then include .inl or better simply .h files that contain the code. Self including .c files is just weird.

**Comment by powturbo** [comment]
I'll think about that

**Comment by powturbo** [comment]
This will explode the number of files which results for me more time to manage the complexity of TurboPFor.
For the moment I let this as as and I'll try to comment more.
