### ISSUE TITLE
Alignment and tailing padding requirements for the decoder APIs

### ISSUE THREAD

**Issue by pps83** [powturbo/TurboPFor#59]
I use p4ndec256v32 and p4nzdec256v32 in my project and I'm not sure if these require any data alignment (for input and output buffers) and if there is any padding requirements. E.g. if these functions may read past the end of the buffer (and how much if they do?) and if the trailing bytes have to be zero filled or it's ok for them to be random?

**Comment by powturbo** [comment]
- Alignment for input and output is not required
- Trailing bytes must no be set to anything. Just call encode and store your the output buffer with the
  length returned.
- p4ndec256v32 and p4nzdec256v32 can read and write up to 32 integers beyond the input/output buffer.
For encoding you can use:
#define P4NENC256_BOUND(n) ((n + 255) /256 + (n + 32) * sizeof(uint32_t))  
For decoding just add 32*4 bytes when allocating the input/output buffer
