### ISSUE TITLE
Shouldn't P4NENC return n if n is 0

### ISSUE THREAD

**Issue by pps83** [powturbo/TurboPFor#61]
https://github.com/powturbo/TurboPFor/blob/672b92534261e530de9271cc5661868b776a8495/vp4c.c#L409

**Comment by powturbo** [comment]
Yes, of course. Thank you, corrected now!

**Comment by pps83** [comment]
FYI, when you commit and add `fixes #61` at the bottom of your commit message github automatically closes the issue and adds a link to the commit that fixed it.

**Comment by pps83** [comment]
fixed by 6629f01a6b03f15a5809088d668b5bc27e873b55
