### ISSUE TITLE
Compress ratio < 7z

### ISSUE THREAD

**Issue by KaiWangCanada** [powturbo/TurboPFor#63]
Tested TP and 7z on 16 bit unsigned bit data. Seems that the best TP algorithm's compress ratio < 7z.
TP: 33.1, 7z: 32.7
TP: 55.2, 7z: 51.2

**Comment by powturbo** [comment]
Integer compression is not designed to have  the best compression ratio, but mainly for speed. 
7z is very slow, compression is in the range 1MB/s and decompression speed in the range of 50MB/s. TurboPFor compression and decompression speed is > 1GB/s. The use case for integer compression is not archiving but in memory databases, seach engines,... where speed is more important than compression ratio.

**Comment by lemire** [comment]
If I may...

It is a multidimensional problem. Some cars go fast, other cars are strong, other cars save gaz... No matter which car you pick, some other car is going to be better according to some criterion.

The same applies to compression. There are various trade-offs and no one compression technique is best at all things. 

It makes it complicated, but then that is why engineers are well paid.

**Comment by KaiWangCanada** [comment]
Thanks so much for the clarification :) 

It is amazing that TPF is so much faster than 7z!

Thanks for the wonderful work :)
