### ISSUE TITLE
a question about licence

### ISSUE THREAD

**Issue by yangzhg** [powturbo/TurboPFor#65]
Hi I am very intrested in your PFor and RLE repo. What is the licence of PFor and RLE， and may i use them in open source project？

**Comment by powturbo** [comment]
License is GPL. You can find the license at the top of each file.
Yes, you can use TurboPFor or TurboRLE in open source project. Please, read the GPL license.

**Comment by halayli** [comment]
@powturbo any reason you chose GPL instead of MIT or BSD ?
