### ISSUE TITLE
direct access after using p4n*enc**

### ISSUE THREAD

**Issue by kcajf** [powturbo/TurboPFor#68]
Hi - if I've compressed a large number of integers with one of the `n` functions, is there any way to directly access a block of integers in the middle? For example, suppose I have 1 million integers and I want to read the integers starting at offset 500,000.

**Comment by powturbo** [comment]
You can store the start of each block (128 or 256 integers) in an offset array.
See the "inverted index demo" programs [idxcr](https://github.com/powturbo/TurboPFor-Integer-Compression/blob/master/idxcr.c#L123).
