### ISSUE TITLE
Licence and others

### ISSUE THREAD

**Issue by rom3r4** [powturbo/TurboPFor#7]
Hello, 

First of all, sorry for my english,

Currently, I am finishing a thesis, and your implementation is cited in the bibliography. For doing this I would like to know some data about your code, 
- What are the differences between your code (the PFOR codec) and other state-of-the-art implementations like D. Lemire et al? http://arxiv.org/pdf/1401.6399v12.pdf 
  - Are the optimizations based on the implementation?, or has the algorithm changed? 
- Is this code part of any published work (e.g article, thesis, etc) which can be cited using a reference  manager?
- What is the licence of your code? (in the case it has any)

Thank-you,
Julian

**Comment by lemire** [comment]
@julianromera 

Though this is not the answer you are looking for, here are some references you might need or be interested in...
- Daniel Lemire, Nathan Kurz, Leonid Boytsov, SIMD Compression and the Intersection of Sorted Integers, Software: Practice and Experience (to appear, http://arxiv.org/abs/1401.6399).
- Jeff Plaisance, Nathan Kurz, Daniel Lemire, Vectorized VByte Decoding, International Symposium on Web Algorithms 2015, 2015 (http://arxiv.org/abs/1503.07387)
- Daniel Lemire and Leonid Boytsov, Decoding billions of integers per second through vectorization, Software: Practice & Experience 45 (1), 2015. http://dx.doi.org/10.1002/spe.2203
- Wayne Xin Zhao, Xudong Zhang, Daniel Lemire, Dongdong Shan, Jian-Yun Nie, Hongfei Yan, Ji-Rong Wen, A General SIMD-based Approach to Accelerating Compression Algorithms, ACM Transactions on Information Systems 33 (3), 2015. http://arxiv.org/abs/1502.01916

**Comment by rom3r4** [comment]
Hello Daniel, thanks for taking the time to write to me. It was a nice surprise because a lot of my thesis is focused in work you have already done. 

Thanks for the links, those are very useful to me.

Have a good evening,
Julian

**Comment by powturbo** [comment]
Glad you have interest on the TurboPFor package.
- The "TurboPFor" function is a novel PFOR/PFORDELTA scheme and uses fixed bit packing for the values and exceptions + flags bitmap indicating an exception. 
  In my benchmarks, it is more efficient than any other fast integer compression scheme. Additionally direct-access (without decompression) to individual values is possible. 
  The FastPFor scheme has a major drawback, it needs large blocks to be efficient (In general 64K integers). Large blocks involved, while processing queries (inverted index, search engines, databases, graphs, in memory computing,...) need to be entirely decoded. Small blocks with fixed size (ex. 128 Integers) like in TurboPFor are usually used. This permits avoiding the decompression of blocks which are not necessary for answering queries. 
  Ex. in the "Inverted Index App" included in TurboPFor, only 10% are decompressed in query processing. 
  Although, the FastPFor package is including several other interesting schemes and optimizations.
- Actually there is no published work about TurboPFor. Most of the functions are optimization (incl. SIMD) or variation of already published work. The references in the readme file or the kindly provided by Daniel are very interesting. 
- TurboPFor is licensed under GPL (see the coding files)

Übrigens, Sie können mir auch in Deutsch mailen, wenn Sie möchten. 

P.S. Daniel, thanks again for your contribution et Joyeux Noël

**Comment by rom3r4** [comment]
Hello @powturbo , thank-you for your input. That is very useful,

Julian

**Comment by lemire** [comment]
@julianromera Make sure to get in touch when your thesis is completed.

**Comment by rom3r4** [comment]
Will do
