### ISSUE TITLE
problem about decode

### ISSUE THREAD

**Issue by zhaojin1997** [powturbo/TurboPFor#72]
Hello ! I want to run the decode parts on the GPU, such as the p4nzdec64 function , so I need to separate out this part of the code.However, vp4d.c and vint.c contain so many TEMPLATE functions that it is difficult for me to accurately locate the p4nzdec64 function. So I would like to ask if I want to separate p4nzdec64 from your code, could you give me some suggestions?

**Comment by spcxtesla** [comment]
Maybe you can use the compiler to preprocess the code

**Comment by powturbo** [comment]
As spcxtesla stated, you can preprocess the "c" files with the command "gcc -E" to generate a version without the templates
