### ISSUE TITLE
Random Access

### ISSUE THREAD

**Issue by linuslh1996** [powturbo/TurboPFor#73]
Hey,
in your description you state that you offer Direct/Random Access for some of your codecs. With Random Access I understand something like this (written in pseudocode):
````
uint_32t single_value = decoded.get(i) // get integer at i-th position
````
Now I wonder, if you do offer Random Access, could you provide a concrete example on how to call your library to get that?

**Comment by powturbo** [comment]
see the [plugins](https://github.com/powturbo/TurboPFor-Integer-Compression/blob/41199d366561aed4571f3401ee72e6ef9659666f/plugins.cc#L312) file for direct access bitpack or the [vp4d](https://github.com/powturbo/TurboPFor-Integer-Compression/blob/41199d366561aed4571f3401ee72e6ef9659666f/vp4d.c#L515) file for turbopfor direct access
