### ISSUE TITLE
Illegal Instruction

### ISSUE THREAD

**Issue by linuslh1996** [powturbo/TurboPFor#74]
When I execute the example from Readme:
````
./icapp -Ft ts.txt -I15 -J15
````
I immediately get the error "Illegal Instruction".

The command was executed under Ubuntu 20.04 with an Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz, after executing `make`.
Under MacOS, the library works however. Does anyone have an idea what could be the issue?

**Comment by spcxtesla** [comment]
Use lscpu to view the extended instruction set supported by the cpu. Check the coredump file to find the illegal instruction

**Comment by powturbo** [comment]
It's too late for a response, but... Your CPU is supporting AVX2 and icapp should normally work. Try the new [icapp ](https://github.com/powturbo/TurboPFor-Integer-Compression/releases/tag/2023.03) and execute it with the option "-v2". It prints the message "detected simd..." with the detected cpu. See if it's corresponding to your cpu. Try also the command "icapp ZIPF" .
