### ISSUE TITLE
GPL requires the repo to contain a license file with unmodified text of GPL

### ISSUE THREAD

**Issue by KOLANICH** [powturbo/TurboPFor#77]

**Comment by jean343** [comment]
Would it be possible to use a different License other than GPL? This would make it possible to integrate this awesome library in commercial products.

**Comment by KOLANICH** [comment]
I guess it is a separate issue.

BTW, you already can integrate it into commercial products. It is not under AGPL.

**Comment by olenz** [comment]
The code states "GPL v2 License", and GPL v2 is too restricted for commercial products.
I think that it is fine that this repo uses GPLv2, but maybe it would be possible that the author can sell a version with a different license?

**Comment by pps83** [comment]
> The code states "GPL v2 License", and GPL v2 is too restricted for commercial products. I think that it is fine that this repo uses GPLv2, but maybe it would be possible that the author can sell a version with a different license?

@olenz https://github.com/lemire/FastPFor is apache licensed.

**Comment by olenz** [comment]
Note that the author is willing to sell commercial licenses. Contact him directly if you want to do so.
