### ISSUE TITLE
a bug in icapp.c:1014

### ISSUE THREAD

**Issue by BeeBreeze** [powturbo/TurboPFor#79]
#define MINDELTA(_t_, _in_, _n_, _dmin_) {\
  _t_ *_p = (_t_ *)_in_, _i;\
  for(_dmin_ = (_t_)-1, _i = 1; _i < _n_; _i++)\
    if(_p[_i] < _p[_i-1]) { dmin = (_t_)-1; break; }\
    else { _t_ _d = _p[_i] - _p[_i-1]; if(_d < _dmin_) { _dmin_ = _d; /*printf("[%u]", _dmin_);*/} }\
}
Note that, the type of _n_ is unsigned, while _t_ may be uint8_t. That is to say,  0\leq _i \leq 255, which leads to that the loop will never end. I think the type of _i should be the same as that of n.

**Comment by powturbo** [comment]
Fixed. Thank you.
