### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [powturbo/TurboPFor#8]
I would like to point out that an identifier like "[`__bx`](https://github.com/powturbo/TurboPFor/blob/a705a02a7647d7cf18ec6ff4217d206b7012a6e2/vp4dc.h#L27)" [does eventually not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier) to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by powturbo** [comment]
thanks for your note. I will adjusted TurboPFor at the next update

**Comment by elfring** [comment]
Will it be better to keep this issue open until it will be really fixed?

**Comment by powturbo** [comment]
TurboPFor updated. Thank you.
