### ISSUE TITLE
TurboPFor fails to build with latest VS 2022 compiler

### ISSUE THREAD

**Issue by pps83** [powturbo/TurboPFor#83]
These are the errors:
```
1>bitutil.h(193,31): warning C4391: 'uint16_t _mm_cvtsi128_si16(__m128i)': incorrect return type for intrinsic function, expected 'short' (compiling source file ..\..\bitpack.c)
1>bitutil.h(193,60): error C2169: '_mm_cvtsi128_si16': intrinsic function, cannot be defined (compiling source file ..\..\bitpack.c)
```

**Comment by MonteCreasor** [comment]
Build issues on Ubuntu 20.04 too (and many more, I'm only including the first error):

bitutil.c: In function ‘bitddec32’:
bitutil.c:213:10: error: incompatible types when assigning to type ‘__m128i’ {aka ‘__vector(2) long long int’} from type ‘int’
  213 |     vs = mm_scan_epi32(v, vs);
      |          ^~~~~~~~~~~~~

**Comment by powturbo** [comment]
There is now a new vs2022 project.
