### ISSUE TITLE
How TurboPfor supports RandomAccess and its benchmarking script

### ISSUE THREAD

**Issue by bluecat1024** [powturbo/TurboPFor#85]
Hi,

You have demonstrated in the results that TurboPfor can reach a good compression rate with random accesses. However, I have only observed the enc/dec logic of whole blocks in the high level API in the source code.

May I ask about what kinds of API supports sequential iteration or random access, and what are some demos  using them? Also, I want to ask whether 64 bit integers are supported or not?

Thanks a lot!

**Comment by powturbo** [comment]
see the [plugins](https://github.com/powturbo/TurboPFor-Integer-Compression/blob/41199d366561aed4571f3401ee72e6ef9659666f/plugins.cc#L312) file for direct access [bitpack ](https://github.com/powturbo/TurboPFor-Integer-Compression/blob/41199d366561aed4571f3401ee72e6ef9659666f/include_/bitpack.h#L180)or the [vp4d](https://github.com/powturbo/TurboPFor-Integer-Compression/blob/41199d366561aed4571f3401ee72e6ef9659666f/vp4d.c#L515) file for turbopfor direct access.
There is actually no direct access to 64-bits integer arrays.
