### ISSUE TITLE
Improve const-correctness

### ISSUE THREAD

**Issue by elfring** [powturbo/TurboPFor#9]
I suggest to add the key word "const" to the type specifiers for parameters like "in" (function "[p4denc32](https://github.com/powturbo/TurboPFor/blob/a705a02a7647d7cf18ec6ff4217d206b7012a6e2/vp4dc.h#L35)").
Would you like to apply the advices from [an article](https://en.wikipedia.org/w/index.php?title=Const_%28computer_programming%29#Consequences) to more places in your source files?

**Comment by powturbo** [comment]
thanks for your note. I will adjusted TurboPFor at the next update

**Comment by elfring** [comment]
Will it be better to keep this issue open until it will be really fixed?

**Comment by powturbo** [comment]
TurboPFor updated. Thank you.
